########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 3/23/2016
#
# Common Gcc Makefile for lamna executable fllhello
########################################################################

fllhello_EXE_CPP_SOURCES += \
${LAMNA_SRC}/lamna/app/gui/fl/hello/main.cpp \
${LAMNA_SRC}/lamna/gui/fl/window.cpp \
${LAMNA_SRC}/lamna/gui/fl/widget.cpp \
${LAMNA_SRC}/lamna/gui/fl/fl.cpp \
${LAMNA_SRC}/lamna/console/main_opt.cpp \
${LAMNA_SRC}/lamna/console/main_main.cpp \


fllhello_EXE_CPP_SOURCES += \
${LAMNA_SRC}/lamna/graphic/surface/fl/color.cpp \
${LAMNA_SRC}/lamna/graphic/surface/fl/object.cpp \
${LAMNA_SRC}/lamna/graphic/surface/fl/image.cpp \
${LAMNA_SRC}/lamna/graphic/surface/fl/context.cpp \
${LAMNA_SRC}/lamna/graphic/surface/fl/pixel.cpp \
${LAMNA_SRC}/lamna/graphic/surface/filled_circle.cpp \
${LAMNA_SRC}/lamna/graphic/hollow_midpoint_ellipse.cpp \
${LAMNA_SRC}/lamna/graphic/hollow_midpoint_circle.cpp \
${LAMNA_SRC}/lamna/graphic/midpoint_ellipse.cpp \
${LAMNA_SRC}/lamna/graphic/midpoint_circle.cpp \
${LAMNA_SRC}/lamna/graphic/triangle.cpp \
${LAMNA_SRC}/lamna/graphic/bresenham_line_context.cpp \
${LAMNA_SRC}/lamna/graphic/bresenham_line.cpp \
${LAMNA_SRC}/lamna/graphic/image_point.cpp \
${LAMNA_SRC}/lamna/graphic/image_base.cpp \
${LAMNA_SRC}/lamna/graphic/list.cpp \

#
# Executable C sources
#
fllhello_EXE_C_SOURCES = \

#
# Executable C++ .cxx sources
#
fllhello_EXE_CXX_SOURCES = \

#
# Executable C++ .cpp sources
#

#
# Executable Objective C sources
#
fllhello_EXE_M_SOURCES = \

#
# Executable Objective C++ sources
#
fllhello_EXE_MM_SOURCES = \

