########################################################################
# Copyright (c) 1988-2016 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 3/24/2016
#
# Common Gcc Makefile for lamna executable xlhello
########################################################################

#
# Executable C++ .cpp sources
#
xlhello_EXE_CPP_SOURCES += \
${LAMNA_SRC}/lamna/gui/x11/main_window.cpp \
${LAMNA_SRC}/lamna/gui/x11/window.cpp \
${LAMNA_SRC}/lamna/gui/x11/colormap.cpp \
${LAMNA_SRC}/lamna/gui/x11/xcolor.cpp \
${LAMNA_SRC}/lamna/gui/x11/region.cpp \
${LAMNA_SRC}/lamna/gui/x11/rectangle.cpp \
${LAMNA_SRC}/lamna/gui/x11/gc.cpp \
${LAMNA_SRC}/lamna/gui/x11/atom.cpp \
${LAMNA_SRC}/lamna/gui/x11/display.cpp \
${LAMNA_SRC}/lamna/gui/x11/screen.cpp \
${LAMNA_SRC}/lamna/gui/x11/event.cpp \
${LAMNA_SRC}/lamna/gui/x11/event_target.cpp \
${LAMNA_SRC}/lamna/gui/x11/created.cpp \
${LAMNA_SRC}/lamna/gui/x11/attached.cpp \
${LAMNA_SRC}/lamna/gui/x11/attacher.cpp \
${LAMNA_SRC}/lamna/gui/x11/x11.cpp \
${LAMNA_SRC}/lamna/gui/x11/gl.cpp \

xlhello_EXE_CPP_SOURCES += \
${LAMNA_SRC}/lamna/graphic/surface/x11/color.cpp \
${LAMNA_SRC}/lamna/graphic/surface/x11/object.cpp \
${LAMNA_SRC}/lamna/graphic/surface/x11/image.cpp \
${LAMNA_SRC}/lamna/graphic/surface/x11/context.cpp \
${LAMNA_SRC}/lamna/graphic/surface/x11/pixel.cpp \

xlhello_EXE_CPP_SOURCES += \
${LAMNA_SRC}/lamna/app/gui/x11/hello/main.cpp \
${LAMNA_SRC}/lamna/gui/x11/window_main.cpp \
${LAMNA_SRC}/lamna/console/main_opt.cpp \
${LAMNA_SRC}/lamna/console/main_main.cpp \

#
# Executable C sources
#
xlhello_EXE_C_SOURCES += \

#
# Executable C++ .cxx sources
#
xlhello_EXE_CXX_SOURCES += \

#
# Executable Objective C sources
#
xlhello_EXE_M_SOURCES += \

#
# Executable Objective C++ sources
#
xlhello_EXE_MM_SOURCES += \

